[package]
name = "crossd-math"

authors.workspace = true
license.workspace = true
version.workspace = true
edition.workspace = true

repository.workspace = true

[dependencies]
bytemuck = "1.14.0"
mint = "0.5.9"

[dev-dependencies]
anyhow = "1.0.75"
pollster = "0.3.0"
