group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
max_width = 90
use_small_heuristics = "Max"

wrap_comments = true
normalize_comments = true
format_code_in_doc_comments = true

reorder_impl_items = true
use_field_init_shorthand = true
format_strings = true
match_block_trailing_comma = true
